#cloud-config

package_upgrade: true

packages:
  - nfs-common
  - xfce4
  - xfce4-session
  - xrdp

runcmd:
  - echo "Starting remote desktop installation via runcmd at $(date +%H:%M:%C)"
  # Based on https://linuxize.com/post/how-to-install-xrdp-on-ubuntu-20-04/
  - 'sudo systemctl enable xrdp'
  - 'sudo echo xfce4-session >~/.xsession'
  - 'sudo service xrdp restart'
  